### PR TITLE
OFFAPPS-391 Time elapses incorrectly

### PR DESCRIPTION
**Pull request by princemaple**
:koala:

Change how time increments

/cc @zendesk/quokka

### Reference
- [JIRA OFFAPPS-391](https://zendesk.atlassian.net/browse/OFFAPPS-391)

### Risks
- N/A

### CODE REVIEW

**Comment by princemaple** [comment]
:haircut: @zendesk/quokka

**Comment by atroche** [comment]
tests

**Comment by atroche** [comment]
jklol :+1:

**Comment by adammw** [comment]
Kinda strange the indirection, but sure. :+1:

**Comment by princemaple** [comment]
Indirection?

**Pull request merged**
