### PR TITLE
added translations for PR #58 - hide app from agents

### PR DESCRIPTION
**Pull request by jstjoe**

### CODE REVIEW

**Comment by jstjoe** [comment]
@pdeuter the code PR has been merged, please let me know if there are any issues with this translation PR

**Comment by pdeuter** [comment]
@jstjoe it doesn't look like any of these strings have been added to the en.yml file.  Here is an article which describes the process: https://support.zendesk.com/hc/en-us/articles/205589027

**Comment by jstjoe** [comment]
Oh shoot I thought we just needed the JSON, my bad. Thanks for the doc, will update.

**Comment by sandlerr** [comment]
should be able to use `zat translate:to_yml` or similar cc @ocke

**Comment by jstjoe** [comment]
Okay yml created via 'zat translate to_yml' @pdeuter 
commit: https://github.com/zendesk/timetracking_app/commit/380c8c06e8b93d05505673b34755c2e1832a70ab

**Comment by pdeuter** [comment]
String is tomorrow morning.  This yml file should be included without any extra effort. I will check it tomorrow.

**Comment by jstjoe** [comment]
Hey @pdeuter let me know if there's anything I can do to help this along?

**Comment by maximeprades** [comment]
@pdeuter let us know if there is anything we should do to get this merged?

**Comment by pdeuter** [comment]
+1

**Comment by pdeuter** [comment]
I will go ahead and merge.

**Comment by maximeprades** [comment]
thanks paul

**Comment by pdeuter** [comment]
Normally the development team will give the +1.  Then the PR is merged.  Then the strings will be swept the following Friday.
Then the translation occurs the following week.  The translations are available the following Thurs.

**Pull request merged**
